// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCph0pDnUeBB5ffiagA44-gmnls4Mtrn_k',
    appId: '1:456308410775:web:e095df81d4133bb3211cd2',
    messagingSenderId: '456308410775',
    projectId: 'crudify-firebase',
    authDomain: 'crudify-firebase.firebaseapp.com',
    storageBucket: 'crudify-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu5XOQgT5AmsLxAUscr96LZ8csF_YCddU',
    appId: '1:456308410775:android:2b62ba48ac92e777211cd2',
    messagingSenderId: '456308410775',
    projectId: 'crudify-firebase',
    storageBucket: 'crudify-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM5yrP5jC7iPWhYFic4P6P8i_NupI_yKM',
    appId: '1:456308410775:ios:6e5f71e5ef559dc7211cd2',
    messagingSenderId: '456308410775',
    projectId: 'crudify-firebase',
    storageBucket: 'crudify-firebase.firebasestorage.app',
    iosBundleId: 'com.example.crudify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM5yrP5jC7iPWhYFic4P6P8i_NupI_yKM',
    appId: '1:456308410775:ios:6e5f71e5ef559dc7211cd2',
    messagingSenderId: '456308410775',
    projectId: 'crudify-firebase',
    storageBucket: 'crudify-firebase.firebasestorage.app',
    iosBundleId: 'com.example.crudify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCph0pDnUeBB5ffiagA44-gmnls4Mtrn_k',
    appId: '1:456308410775:web:963c99e77bdcac7f211cd2',
    messagingSenderId: '456308410775',
    projectId: 'crudify-firebase',
    authDomain: 'crudify-firebase.firebaseapp.com',
    storageBucket: 'crudify-firebase.firebasestorage.app',
  );
}
